Enable invokes customized methods
henrique-gouveia/DataQI.Dapper.FastCrud pull request #20
Opened 2021-10-10 14:38 UTC by henrique-gouveia

- changed TEntity requirements on IDapperRepository interface
- added support for new repository factory definitions
- enabled invokes customized methods
- Migrate to GitHub Actions

2021-10-31 13:24 UTC, ypedroo requested changes

2021-10-31 13:24 UTC, ypedroo commented on src/DataQI.Dapper.FastCrud/Query/Extensions/DapperCriterionExtensions.cs
>              switch (criterion.GetWhereOperator())
Could use pattern matching here.
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/pattern-matching#compare-discrete-values

2021-10-31 13:24 UTC, ypedroo commented on test/DataQI.Dapper.FastCrud.Test/Fixtures/DbFixture.cs
> +            // CustomerRepository = new CustomerRepository(Connection);
remove commented out code

2021-10-31 13:24 UTC, ypedroo commented on test/DataQI.Dapper.FastCrud.Test/Fixtures/DbFixture.cs
> +            // CustomerRepository = new CustomerRepository(Connection);
if documentation should be on the docs

2021-10-31 13:24 UTC, ypedroo commented on test/DataQI.Dapper.FastCrud.Test/Fixtures/DbFixture.cs
> +                    .Append(SqlResource.CUSTOMER_CREATE_SCRIPT)
template string could also be applied

2021-10-31 13:24 UTC, ypedroo commented on test/DataQI.Dapper.FastCrud.Test/Repository/Customers/CustomerBuilder.cs
> +        public Customer Build() => customer;
Just a question, why the set syntax sugar was not an option for this purpose?

2021-10-31 13:24 UTC, ypedroo commented on test/DataQI.Dapper.FastCrud.Test/Repository/DapperRepositoryQueryMethodTest.cs
> +                var productNameStartsWith = product.Name.Substring(0, 5);
could use c# range

2021-10-31 13:24 UTC, ypedroo commented on test/DataQI.Dapper.FastCrud.Test/Repository/DapperRepositoryQueryMethodTest.cs
> +                var productNameStartsWith = product.Name.Substring(0, 5);
```suggestion
                var productNameStartsWith = product.Name[..5];
```

2021-10-31 13:24 UTC, ypedroo commented on test/DataQI.Dapper.FastCrud.Test/Repository/DapperRepositoryTest.cs
> +            Assert.True(customerExpected.Id > 0);
use assertion scope on multiple assertions

2021-10-31 13:24 UTC, ypedroo commented on test/DataQI.Dapper.FastCrud.Test/Repository/DapperRepositoryTest.cs
> +                Assert.False(ExistsCustomer(customer, useAsyncMethod));
use assertion scope on multiple assertions

2022-01-05 19:34 UTC, henrique-gouveia commented on src/DataQI.Dapper.FastCrud/Query/Extensions/DapperCriterionExtensions.cs
>              switch (criterion.GetWhereOperator())
I could, but look: 

The library is built around .NET Standard 2.0 'cause I wanna to keep a retro compatibility with .NET Framework 4 or less. See https://docs.microsoft.com/en-us/dotnet/standard/net-standard

.NET Standard 2.0 supports C# 7.3 and to use this feature, probably, I would need .NET Standard 2.1 that supports C# 8.0. See https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

2022-01-05 19:38 UTC, henrique-gouveia commented on test/DataQI.Dapper.FastCrud.Test/Fixtures/DbFixture.cs
> +                    .Append(SqlResource.CUSTOMER_CREATE_SCRIPT)
Yes, It make sense.

2022-01-05 19:48 UTC, henrique-gouveia commented on test/DataQI.Dapper.FastCrud.Test/Repository/Customers/CustomerBuilder.cs
> +        public Customer Build() => customer;
This class is a Data Builder that has the function of encapsulating building clients with random data, but I don't rule out ways to improve otherwise, we can talk about ideas at some point.

2022-01-05 19:50 UTC, henrique-gouveia commented on test/DataQI.Dapper.FastCrud.Test/Repository/DapperRepositoryQueryMethodTest.cs
> +                var productNameStartsWith = product.Name.Substring(0, 5);
As I said, I'm trying to keep using only C#7.3 features.

2022-01-05 19:51 UTC, henrique-gouveia commented on test/DataQI.Dapper.FastCrud.Test/Repository/DapperRepositoryQueryMethodTest.cs
> +                var productNameStartsWith = product.Name.Substring(0, 5);
As I said, I'm trying to keep using only C#7.3 features.

2022-01-05 19:53 UTC, henrique-gouveia commented on test/DataQI.Dapper.FastCrud.Test/Repository/DapperRepositoryTest.cs
> +            Assert.True(customerExpected.Id > 0);
This is just a way to confirm that the customer has inserted into arrange part of the unit test.

2022-01-05 19:53 UTC, henrique-gouveia commented on test/DataQI.Dapper.FastCrud.Test/Repository/DapperRepositoryTest.cs
> +                Assert.False(ExistsCustomer(customer, useAsyncMethod));
This is just a way to confirm that the customer has inserted into arrange part of the unit test.

2022-01-06 12:11 UTC, ypedroo approved these changes

2022-01-08 12:59 UTC, merged